[Defaults]
hiresStep = 4200
hiresEncoder = 277
loresStep = 278600
loresEncoder = 4064
loresSwapStep = 80000
loresSwapEncoder = 1286
gesTolerance = 7
filter1encoder = 75.5
filter2encoder = 371
filter3encoder = 665
filter4encoder = 953.5
filter5encoder = 1242.5
filter6encoder = 1526
filter7encoder = 1807
filter8encoder = 2088
filter9encoder = 3789
filterRemoved = 60
filterTolerance = 14
